apiVersion: batch/v1
kind: CronJob
metadata:
  name: icon-eu-h-snow-job
  namespace: pt
spec:
  schedule: "13 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: prepare
              image: "ghcr.io/dzfranklin/weather-maps:latest"
              command: [ "python", "icon_eu_h_snow.py" ]
              env:
                - name: BUNNY_KEY
                  valueFrom:
                    secretKeyRef:
                      name: bunny
                      key: key
                - name: BUNNY_WEATHER_STORAGE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: bunny
                      key: weather_storage_key
          restartPolicy: OnFailure
